//
//  AppDelegate.m
//  FinderToys
//
//  Created by Louie Yin on 2026-01-25.
//

#import "AppDelegate.h"
#import <ServiceManagement/ServiceManagement.h>
#import <ApplicationServices/ApplicationServices.h>

static inline NSString *FTAppLocalizedString(NSString *key) {
    static NSBundle *bundle = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSBundle *mainBundle = [NSBundle mainBundle];
        NSArray *preferred = [NSBundle preferredLocalizationsFromArray:[mainBundle localizations] forPreferences:[NSLocale preferredLanguages]];
        NSString *lang = preferred.firstObject ?: @"en";
        NSString *path = [mainBundle pathForResource:lang ofType:@"lproj"];
        if (path) {
            bundle = [NSBundle bundleWithPath:path];
        }
        if (!bundle) {
            bundle = mainBundle;
        }
    });
    return [bundle localizedStringForKey:key value:key table:nil];
}
#undef NSLocalizedString
#define NSLocalizedString(key, comment) FTAppLocalizedString(key)

static NSString * const kEnterToOpenDefaultsKey = @"EnterToOpenInFinder";
static NSString * const kPasteClipboardDefaultsKey = @"PasteClipboardToFileInFinder";
#define FT_SYNTHETIC_TAG 0x465453 // 'MNF'

static CFMachPortRef sEventTap = NULL;
static CFRunLoopSourceRef sRunLoopSource = NULL;

static BOOL sIsSynthesizing = NO;

@interface AppDelegate ()
@property (strong) NSStatusItem *statusItem;
@property (strong) NSMenuItem *enterToOpenMenuItem;
@property (strong) NSMenuItem *pasteClipboardMenuItem;
@property (strong) NSMenuItem *accessibilityMenuItem;
@property (strong) NSTimer *accessibilityPollTimer;

+ (BOOL)handlePasteInFinder;
+ (NSString *)currentFinderFolderPath;
+ (NSString *)uniqueFilePathInDirectory:(NSString *)dir baseName:(NSString *)base extension:(NSString *)ext;
+ (void)revealAndSelectPath:(NSString *)filePath;
@end

static CGEventRef eventTapCallback(CGEventTapProxy proxy, CGEventType type, CGEventRef event, void *refcon) {
    if (type == kCGEventTapDisabledByTimeout || type == kCGEventTapDisabledByUserInput) {
        if (sEventTap) {
            CGEventTapEnable(sEventTap, true);
        }
        return event;
    }

    if (type != kCGEventKeyDown) {
        return event;
    }

    if (sIsSynthesizing) {
        return event;
    }

    // Ignore synthetic events generated by MacNewFile
    if (CGEventGetIntegerValueField(event, kCGEventSourceUserData) == FT_SYNTHETIC_TAG) {
        return event;
    }

    // Only intercept when Finder is the frontmost application
    NSRunningApplication *frontApp = [[NSWorkspace sharedWorkspace] frontmostApplication];
    if (![frontApp.bundleIdentifier isEqualToString:@"com.apple.finder"]) {
        return event;
    }

    CGEventFlags flags = CGEventGetFlags(event);

    BOOL hasCmd = (flags & kCGEventFlagMaskCommand) != 0;
    BOOL hasShift = (flags & kCGEventFlagMaskShift) != 0;
    BOOL hasAlt = (flags & kCGEventFlagMaskAlternate) != 0;
    BOOL hasCtrl = (flags & kCGEventFlagMaskControl) != 0;

    CGKeyCode keyCode = (CGKeyCode)CGEventGetIntegerValueField(event, kCGKeyboardEventKeycode);
    BOOL isReturnKey = (keyCode == 36 || keyCode == 76);
    BOOL isCmdR = (keyCode == 15 && hasCmd && !hasShift && !hasAlt && !hasCtrl);
    BOOL isF2Trigger = (keyCode == 120 || keyCode == 144) && !hasCmd && !hasCtrl;
    BOOL isCmdV = (keyCode == 9 && hasCmd && !hasShift && !hasAlt && !hasCtrl);
    BOOL isOptOrShiftReturn = isReturnKey && (hasAlt || hasShift) && !hasCmd && !hasCtrl;

    // Fast-path: if not a key we care about, pass through immediately with zero overhead!
    if (!isReturnKey && !isCmdR && !isF2Trigger && !isCmdV) {
        return event;
    }

    // Check if user is currently typing in an editable field (renaming a file, searching, or in Go to folder)
    BOOL isEditingText = NO;
    AXUIElementRef systemWide = AXUIElementCreateSystemWide();
    if (systemWide) {
        AXUIElementRef focused = NULL;
        if (AXUIElementCopyAttributeValue(systemWide, kAXFocusedUIElementAttribute, (CFTypeRef *)&focused) == kAXErrorSuccess && focused) {
            CFStringRef role = NULL;
            if (AXUIElementCopyAttributeValue(focused, kAXRoleAttribute, (CFTypeRef *)&role) == kAXErrorSuccess && role) {
                if (CFEqual(role, CFSTR("AXTextField")) || CFEqual(role, CFSTR("AXTextArea")) || CFEqual(role, CFSTR("AXComboBox"))) {
                    isEditingText = YES;
                }
                CFRelease(role);
            }
            CFRelease(focused);
        }
        CFRelease(systemWide);
    }

    BOOL isRenameTrigger = isCmdR || isF2Trigger || isOptOrShiftReturn;
    if (isRenameTrigger) {
        if (isEditingText) {
            return event;
        }

        // Send clean Return directly to Finder PID to trigger native rename without event tap interception
        pid_t finderPid = frontApp.processIdentifier;
        CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStateHIDSystemState);
        CGEventRef down = CGEventCreateKeyboardEvent(source, 36, true); // Return
        CGEventSetFlags(down, 0); // Clean return without modifiers
        CGEventPostToPid(finderPid, down);
        CFRelease(down);

        CGEventRef up = CGEventCreateKeyboardEvent(source, 36, false);
        CGEventSetFlags(up, 0);
        CGEventPostToPid(finderPid, up);
        CFRelease(up);
        CFRelease(source);

        return NULL; // Suppress original trigger
    }

    // 2. Open trigger: Clean Return / Keypad Enter (keyCode 36 or 76) without Cmd, Alt, Ctrl, Shift
    BOOL hasAnyModifier = hasCmd || hasShift || hasAlt || hasCtrl;
    if (isReturnKey && !hasAnyModifier) {
        if (![[NSUserDefaults standardUserDefaults] boolForKey:kEnterToOpenDefaultsKey]) {
            return event;
        }

        if (isEditingText) {
            // In a text field (renaming, search, etc.) - let Return work normally to commit rename!
            return event;
        }

        // Open selected item using Cmd + Down Arrow (keyCode 125) directly to Finder PID
        pid_t finderPid = frontApp.processIdentifier;
        CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStateHIDSystemState);
        CGEventRef down = CGEventCreateKeyboardEvent(source, 125, true);
        CGEventSetFlags(down, kCGEventFlagMaskCommand);
        CGEventPostToPid(finderPid, down);
        CFRelease(down);

        CGEventRef up = CGEventCreateKeyboardEvent(source, 125, false);
        CGEventSetFlags(up, kCGEventFlagMaskCommand);
        CGEventPostToPid(finderPid, up);
        CFRelease(up);
        CFRelease(source);

        return NULL; // Suppress original Return
    }

    // 3. Paste Clipboard -> File: ⌘V (keyCode 9)
    if (keyCode == 9 && hasCmd && !hasShift && !hasAlt && !hasCtrl) {
        if (isEditingText) {
            // When editing text in Finder (e.g. renaming file, search box, Go to folder), let Cmd+V paste text into the field!
            return event;
        }

        if ([[NSUserDefaults standardUserDefaults] boolForKey:kPasteClipboardDefaultsKey]) {
            if ([AppDelegate handlePasteInFinder]) {
                return NULL; // Handled: file created from clipboard! Suppress native paste.
            }
        }
    }

    return event;
}

@implementation AppDelegate

+ (NSString *)currentFinderFolderPath {
    // 1. Accessibility API: get focused or main window's AXDocument attribute from Finder
    // Because FinderToys already has Accessibility permissions, this is instant and doesn't require AppleEvents.
    NSRunningApplication *finderApp = [NSRunningApplication runningApplicationsWithBundleIdentifier:@"com.apple.finder"].firstObject;
    if (finderApp) {
        AXUIElementRef axFinder = AXUIElementCreateApplication(finderApp.processIdentifier);
        if (axFinder) {
            AXUIElementRef targetWindow = NULL;
            // First check focused window
            if (AXUIElementCopyAttributeValue(axFinder, kAXFocusedWindowAttribute, (CFTypeRef *)&targetWindow) != kAXErrorSuccess || !targetWindow) {
                // Fall back to main window
                AXUIElementCopyAttributeValue(axFinder, kAXMainWindowAttribute, (CFTypeRef *)&targetWindow);
            }

            if (targetWindow) {
                CFTypeRef docRef = NULL;
                if (AXUIElementCopyAttributeValue(targetWindow, (CFStringRef)@"AXDocument", &docRef) == kAXErrorSuccess && docRef) {
                    NSString *urlString = [NSString stringWithFormat:@"%@", (__bridge id)docRef];
                    CFRelease(docRef);
                    NSURL *url = [NSURL URLWithString:urlString];
                    if (url && url.isFileURL) {
                        NSString *path = url.path;
                        BOOL isDir = NO;
                        if ([[NSFileManager defaultManager] fileExistsAtPath:path isDirectory:&isDir] && isDir) {
                            CFRelease(targetWindow);
                            CFRelease(axFinder);
                            return path;
                        }
                    }
                }
                CFRelease(targetWindow);
            }
            CFRelease(axFinder);
        }
    }

    // 2. AppleScript: use 'insertion location' (the exact directory where new items are inserted in Finder)
    NSAppleScript *script = [[NSAppleScript alloc] initWithSource:
        @"tell application \"Finder\"\n"
        @"    try\n"
        @"        return POSIX path of (insertion location as alias)\n"
        @"    on error\n"
        @"        try\n"
        @"            return POSIX path of (target of front Finder window as alias)\n"
        @"        on error\n"
        @"            return POSIX path of (path to desktop folder as alias)\n"
        @"        end try\n"
        @"    end try\n"
        @"end tell"];
    NSDictionary *err = nil;
    NSAppleEventDescriptor *desc = [script executeAndReturnError:&err];
    if (desc && desc.stringValue.length > 0) {
        NSString *path = desc.stringValue;
        if ([path hasSuffix:@"/"] && path.length > 1) {
            path = [path substringToIndex:path.length - 1];
        }
        BOOL isDir = NO;
        if ([[NSFileManager defaultManager] fileExistsAtPath:path isDirectory:&isDir] && isDir) {
            return path;
        }
    }

    return [NSHomeDirectory() stringByAppendingPathComponent:@"Desktop"];
}

+ (NSString *)uniqueFilePathInDirectory:(NSString *)dir baseName:(NSString *)base extension:(NSString *)ext {
    NSFileManager *fm = [NSFileManager defaultManager];
    NSString *candidate = [dir stringByAppendingPathComponent:[NSString stringWithFormat:@"%@.%@", base, ext]];
    if (![fm fileExistsAtPath:candidate]) {
        return candidate;
    }
    int count = 2;
    while (true) {
        candidate = [dir stringByAppendingPathComponent:[NSString stringWithFormat:@"%@ %d.%@", base, count, ext]];
        if (![fm fileExistsAtPath:candidate]) {
            return candidate;
        }
        count++;
    }
}

+ (void)revealAndSelectPath:(NSString *)filePath {
    NSURL *fileURL = [NSURL fileURLWithPath:filePath];
    [[NSWorkspace sharedWorkspace] activateFileViewerSelectingURLs:@[fileURL]];
}

+ (BOOL)handlePasteInFinder {
    NSPasteboard *pb = [NSPasteboard generalPasteboard];
    NSArray<NSPasteboardType> *types = pb.types;
    if (!types || types.count == 0) {
        return NO;
    }

    // 1. If pasteboard contains file URLs (e.g., standard files/folders copied in Finder), do NOT intercept!
    // Let Finder perform its native paste!
    if ([types containsObject:NSPasteboardTypeFileURL] || [types containsObject:@"public.file-url"] || [types containsObject:@"NSFilenamesPboardType"]) {
        return NO;
    }

    NSString *targetDir = [self currentFinderFolderPath];
    if (!targetDir || targetDir.length == 0) {
        return NO;
    }

    NSFileManager *fm = [NSFileManager defaultManager];
    if (![fm fileExistsAtPath:targetDir]) {
        return NO;
    }

    // 2. Check for Image data (PNG, TIFF)
    if ([types containsObject:NSPasteboardTypePNG] || [types containsObject:NSPasteboardTypeTIFF] || [pb canReadItemWithDataConformingToTypes:@[@"public.image"]]) {
        NSImage *img = [[NSImage alloc] initWithPasteboard:pb];
        if (img) {
            NSData *pngData = nil;
            for (NSImageRep *rep in img.representations) {
                if ([rep isKindOfClass:[NSBitmapImageRep class]]) {
                    pngData = [(NSBitmapImageRep *)rep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
                    break;
                }
            }
            if (!pngData) {
                CGImageRef cgRef = [img CGImageForProposedRect:NULL context:nil hints:nil];
                if (cgRef) {
                    NSBitmapImageRep *newRep = [[NSBitmapImageRep alloc] initWithCGImage:cgRef];
                    pngData = [newRep representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
                }
            }

            if (pngData && pngData.length > 0) {
                NSString *filePath = [self uniqueFilePathInDirectory:targetDir baseName:@"image" extension:@"png"];

                if ([pngData writeToFile:filePath atomically:YES]) {
                    [self revealAndSelectPath:filePath];
                    return YES;
                }
            }
        }
    }

    // 3. Check for string / URL / JSON / HTML / Plain text
    NSString *stringContent = [pb stringForType:NSPasteboardTypeString];
    if (stringContent && stringContent.length > 0) {
        NSString *trimmed = [stringContent stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];

        // 3A. URL -> create .webloc (only if it's a single line URL without whitespace)
        if (([trimmed hasPrefix:@"http://"] || [trimmed hasPrefix:@"https://"]) &&
            ![trimmed containsString:@"\n"] && ![trimmed containsString:@"\r"] && ![trimmed containsString:@" "]) {
            NSURL *url = [NSURL URLWithString:trimmed];
            if (url && url.host) {
                NSString *host = url.host;
                if ([host hasPrefix:@"www."]) {
                    host = [host substringFromIndex:4];
                }
                NSString *siteName = host.stringByDeletingPathExtension;
                if (siteName.length > 0) {
                    siteName = [siteName capitalizedString];
                } else {
                    siteName = @"Website";
                }

                NSDictionary *weblocDict = @{@"URL": trimmed};
                NSString *filePath = [self uniqueFilePathInDirectory:targetDir baseName:siteName extension:@"webloc"];
                if ([weblocDict writeToFile:filePath atomically:YES]) {
                    [self revealAndSelectPath:filePath];
                    return YES;
                }
            }
        }

        // 3B. JSON -> create .json
        if (([trimmed hasPrefix:@"{"] && [trimmed hasSuffix:@"}"]) ||
            ([trimmed hasPrefix:@"["] && [trimmed hasSuffix:@"]"])) {
            NSData *data = [trimmed dataUsingEncoding:NSUTF8StringEncoding];
            if (data) {
                NSError *jsonErr = nil;
                id jsonObj = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingFragmentsAllowed error:&jsonErr];
                if (jsonObj && !jsonErr) {
                    NSString *filePath = [self uniqueFilePathInDirectory:targetDir baseName:@"Clipboard" extension:@"json"];
                    if ([stringContent writeToFile:filePath atomically:YES encoding:NSUTF8StringEncoding error:nil]) {
                        [self revealAndSelectPath:filePath];
                        return YES;
                    }
                }
            }
        }

        // 3C. HTML -> create .html ONLY if explicitly an HTML document
        NSString *lower = trimmed.lowercaseString;
        BOOL isExplicitHTML = [lower hasPrefix:@"<!doctype html"] || [lower hasPrefix:@"<html"];
        if (isExplicitHTML) {
            NSString *filePath = [self uniqueFilePathInDirectory:targetDir baseName:@"Clipboard" extension:@"html"];
            if ([stringContent writeToFile:filePath atomically:YES encoding:NSUTF8StringEncoding error:nil]) {
                [self revealAndSelectPath:filePath];
                return YES;
            }
        }

        // 3D. Plain text -> create .txt (default for any text, notes, code snippets)
        NSString *filePath = [self uniqueFilePathInDirectory:targetDir baseName:@"Clipboard" extension:@"txt"];
        if ([stringContent writeToFile:filePath atomically:YES encoding:NSUTF8StringEncoding error:nil]) {
            [self revealAndSelectPath:filePath];
            return YES;
        }
    }

    return NO;
}

+ (void)enableF2KeyMapping:(BOOL)enable {
    NSTask *task = [[NSTask alloc] init];
    task.launchPath = @"/usr/bin/hidutil";
    if (enable) {
        // Remap Consumer Brightness Up (0x0C0000006F) to Keyboard F2 (0x070000003B)
        task.arguments = @[@"property", @"--set", @"{\"UserKeyMapping\":[{\"HIDKeyboardModifierMappingSrc\":0x0C0000006F,\"HIDKeyboardModifierMappingDst\":0x070000003B}]}"];
    } else {
        task.arguments = @[@"property", @"--set", @"{\"UserKeyMapping\":[]}"];
    }
    @try {
        [task launch];
        [task waitUntilExit];
        NSLog(@"[FinderToys] F2 key mapping set: %d", enable);
    } @catch (NSException *e) {
        NSLog(@"[FinderToys] Failed to run hidutil: %@", e);
    }
}

- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    // Register defaults
    [[NSUserDefaults standardUserDefaults] registerDefaults:@{
        kEnterToOpenDefaultsKey: @YES,
        kPasteClipboardDefaultsKey: @YES
    }];

    // Enable physical F2 key mapping so F2 and Shift+F2 produce standard F2 without Fn
    [AppDelegate enableF2KeyMapping:YES];

    // Enable the Finder extension
    [self setExtensionEnabled:YES];

    // Create menu bar icon
    self.statusItem = [[NSStatusBar systemStatusBar] statusItemWithLength:NSSquareStatusItemLength];

    NSImage *icon = nil;
    if (@available(macOS 11.0, *)) {
        icon = [NSImage imageWithSystemSymbolName:@"doc.badge.plus" accessibilityDescription:@"FinderToys"];
    }
    if (!icon) {
        icon = [[NSBundle mainBundle] imageForResource:@"add"];
    }
    if (icon) {
        icon.size = NSMakeSize(18, 18);
        icon.template = YES;
        self.statusItem.button.image = icon;
    } else {
        self.statusItem.button.title = @"➕";
    }
    self.statusItem.button.toolTip = @"FinderToys";

    // Create dropdown menu on click
    NSMenu *menu = [[NSMenu alloc] init];
    [menu addItemWithTitle:NSLocalizedString(@"FinderToys is running", nil) action:nil keyEquivalent:@""];
    [menu addItem:[NSMenuItem separatorItem]];

    // Toggle for Enter to open / F2 to rename
    self.enterToOpenMenuItem = [[NSMenuItem alloc] initWithTitle:NSLocalizedString(@"Enter to open in Finder (F2 to rename)", nil)
                                                          action:@selector(toggleEnterToOpen:)
                                                   keyEquivalent:@""];
    self.enterToOpenMenuItem.target = self;
    self.enterToOpenMenuItem.state = [[NSUserDefaults standardUserDefaults] boolForKey:kEnterToOpenDefaultsKey] ? NSControlStateValueOn : NSControlStateValueOff;
    [menu addItem:self.enterToOpenMenuItem];

    // Toggle for Paste Clipboard to file (⌘V)
    self.pasteClipboardMenuItem = [[NSMenuItem alloc] initWithTitle:NSLocalizedString(@"Paste Clipboard to file (⌘V)", nil)
                                                             action:@selector(togglePasteClipboard:)
                                                      keyEquivalent:@""];
    self.pasteClipboardMenuItem.target = self;
    self.pasteClipboardMenuItem.state = [[NSUserDefaults standardUserDefaults] boolForKey:kPasteClipboardDefaultsKey] ? NSControlStateValueOn : NSControlStateValueOff;
    [menu addItem:self.pasteClipboardMenuItem];

    [menu addItem:[NSMenuItem separatorItem]];
    [menu addItemWithTitle:NSLocalizedString(@"Quit", nil) action:@selector(terminate:) keyEquivalent:@"q"];

    self.statusItem.menu = menu;

    // Start event tap for Enter/F2/Cmd+V
    [self setupEventTap];

    // Register application in Login Items as a background app
    if (@available(macOS 13.0, *)) {
        SMAppService *service = [SMAppService mainAppService];
        if (service.status != SMAppServiceStatusEnabled) {
            NSError *error = nil;
            [service registerAndReturnError:&error];
            if (error) {
                NSLog(@"Failed to add to login items: %@", error);
            }
        }
    }
}

- (void)toggleEnterToOpen:(id)sender {
    BOOL current = [[NSUserDefaults standardUserDefaults] boolForKey:kEnterToOpenDefaultsKey];
    BOOL newSetting = !current;
    [[NSUserDefaults standardUserDefaults] setBool:newSetting forKey:kEnterToOpenDefaultsKey];
    self.enterToOpenMenuItem.state = newSetting ? NSControlStateValueOn : NSControlStateValueOff;

    if (newSetting) {
        [self setupEventTap];
    }
}

- (void)togglePasteClipboard:(id)sender {
    BOOL current = [[NSUserDefaults standardUserDefaults] boolForKey:kPasteClipboardDefaultsKey];
    BOOL newSetting = !current;
    [[NSUserDefaults standardUserDefaults] setBool:newSetting forKey:kPasteClipboardDefaultsKey];
    self.pasteClipboardMenuItem.state = newSetting ? NSControlStateValueOn : NSControlStateValueOff;

    if (newSetting) {
        [self setupEventTap];
    }
}

- (void)setupEventTap {
    BOOL isTrusted = AXIsProcessTrusted();
    NSLog(@"[FinderToys] setupEventTap: isTrusted = %d, sEventTap = %p", isTrusted, sEventTap);

    [self updateAccessibilityMenuItemForTrusted:isTrusted];

    if (!isTrusted) {
        // Tear down any stale tap
        [self tearDownEventTap];

        // Show system Accessibility prompt (кидает системный диалог)
        NSDictionary *options = @{(__bridge id)kAXTrustedCheckOptionPrompt: @YES};
        AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)options);

        // Poll until granted - then automatically activate EventTap without restart
        [self startAccessibilityPollingIfNeeded];
        return;
    }

    // Already trusted: ensure tap is live
    if (sEventTap) {
        CGEventTapEnable(sEventTap, true);
        return;
    }

    CGEventMask eventMask = CGEventMaskBit(kCGEventKeyDown);
    sEventTap = CGEventTapCreate(
        kCGSessionEventTap,
        kCGHeadInsertEventTap,
        kCGEventTapOptionDefault,
        eventMask,
        eventTapCallback,
        NULL
    );

    if (!sEventTap) {
        NSLog(@"[FinderToys] Failed to create event tap");
        return;
    }

    sRunLoopSource = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, sEventTap, 0);
    CFRunLoopAddSource(CFRunLoopGetMain(), sRunLoopSource, kCFRunLoopCommonModes);
    CGEventTapEnable(sEventTap, true);
    NSLog(@"[FinderToys] Event tap successfully enabled for Finder Enter/F2/Cmd+V!");

    // Stop any pending polling timer
    [self.accessibilityPollTimer invalidate];
    self.accessibilityPollTimer = nil;
}

- (void)tearDownEventTap {
    if (sEventTap) {
        CGEventTapEnable(sEventTap, false);
        if (sRunLoopSource) {
            CFRunLoopRemoveSource(CFRunLoopGetMain(), sRunLoopSource, kCFRunLoopCommonModes);
            CFRelease(sRunLoopSource);
            sRunLoopSource = NULL;
        }
        CFRelease(sEventTap);
        sEventTap = NULL;
    }
}

- (void)startAccessibilityPollingIfNeeded {
    if (self.accessibilityPollTimer && self.accessibilityPollTimer.isValid) {
        return; // already polling
    }
    __weak typeof(self) weakSelf = self;
    self.accessibilityPollTimer = [NSTimer scheduledTimerWithTimeInterval:1.0 repeats:YES block:^(NSTimer * _Nonnull t) {
        if (AXIsProcessTrusted()) {
            NSLog(@"[FinderToys] Accessibility permission granted!");
            [t invalidate];
            weakSelf.accessibilityPollTimer = nil;
            [weakSelf setupEventTap];
        }
    }];
}

- (void)updateAccessibilityMenuItemForTrusted:(BOOL)trusted {
    if (!self.accessibilityMenuItem) return;
    if (trusted) {
        self.accessibilityMenuItem.title = NSLocalizedString(@"✅ Accessibility: Granted", nil);
        self.accessibilityMenuItem.action = nil;
        self.accessibilityMenuItem.target = nil;
    } else {
        self.accessibilityMenuItem.title = NSLocalizedString(@"⚠️ Grant Accessibility Access…", nil);
        self.accessibilityMenuItem.action = @selector(openAccessibilityPrefs:);
        self.accessibilityMenuItem.target = self;
    }
}

- (void)openAccessibilityPrefs:(id)sender {
    // Prompt the system dialog again, then open System Preferences
    NSDictionary *options = @{(__bridge id)kAXTrustedCheckOptionPrompt: @YES};
    AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)options);
    [[NSWorkspace sharedWorkspace] openURL:[NSURL URLWithString:@"x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"]];
    [self startAccessibilityPollingIfNeeded];
}

- (void)applicationWillTerminate:(NSNotification *)aNotification {
    // Restore default key mappings
    [AppDelegate enableF2KeyMapping:NO];

    [self.accessibilityPollTimer invalidate];
    self.accessibilityPollTimer = nil;

    [self tearDownEventTap];

    // Disable the Finder extension when app quits
    [self setExtensionEnabled:NO];
}

- (void)setExtensionEnabled:(BOOL)enabled {
    NSTask *task = [[NSTask alloc] init];
    task.launchPath = @"/usr/bin/pluginkit";
    task.arguments = @[
        @"-e",
        enabled ? @"use" : @"ignore",
        @"-i",
        @"com.atlant63.FinderToys.FinderToysExtension"
    ];
    [task launch];
    [task waitUntilExit];
}

- (BOOL)applicationSupportsSecureRestorableState:(NSApplication *)app {
    return YES;
}

@end
